### PR TITLE
initial commit for CI build

### PR DESCRIPTION
**Pull request by Murmele**
Setting up the CI build and packaging of the project.

Currently I used dbc as target do you agree with it? (As can be seen in test/TestdbcCMake/CMakeLists.txt, the linked target is dbc and not libdbc)

AUR Package
https://aur.archlinux.org/packages/dbclib-git

### CODE REVIEW

**Comment by Murmele** [comment]
I copied just from the mdflib

**Comment by Murmele** [comment]
image

in message.h

```
void Node(const std::string& node) {
     if (node_.empty()) {
       node_ = node;
     }
     sender_list_.push_back(node);
   }
```

**Comment by Murmele** [comment]
This must be merged first: https://github.com/ihedvall/mdflib/pull/13

**Review by ihedvall — APPROVED** [review]
Looks OK

**Pull request merged**
