### PR TITLE
Add example how to parse a message

### PR DESCRIPTION
**Pull request by Murmele**

### CODE REVIEW

**Comment by Murmele** [comment]
@ihedvall I did not understand yet how I can parse a raw message

**Comment by ihedvall** [comment]
The DBC library have 2 functions. The first function is to parse the DBC file that describe a CAN network. The other function is to parse raw messages into signal values. For example in an MDF CAN logger file, you get time, CAN ID and messgae raw byte. I don't know if the BLF file have more information but assume that you only get time, CAN ID and message bytes.

There is 2 ways you can use the parsing of message bytes. 

Assume you get messages on a bus in real time and you want the signal value. Then you call the DbcFile::ParseMessage() function with the message and then check the signal value with either calling the Signal::ChannelValue() function  or the scaled value with the Signal::EngValue() function. These function return the latest value.

The other method is similar to the above one but now you subscribe on all samples for a specific signal by creating one or more SignalObservers. The observer will actually store channel value for each sample. You should set max number of samples.

Note that this a new library so I haven't tested all types of protocols. The problem is that it is difficult to find matching DBC file and log files to test with, so. expect some pathing inside the ParseMessage() functions.

I have added the DbcViewer code that plots an MDF log file sample values.

`
void ChildFrame::OnPlotSignalData(wxCommandEvent &event) {
  wxBusyCursor wait;
  auto* doc = GetDoc();
  auto* file = doc != nullptr ? doc->GetFile() : nullptr;
  const auto* network = file != nullptr ? file->GetNetwork() : nullptr;
  if (network == nullptr || left_ == nullptr) {
    return;
  }
  const auto selected = left_->GetSelection();
  if (!selected.IsOk()) {
    return;
  }

  const auto* data = dynamic_cast<TreeItemData*>(left_->GetItemData(selected));
  if (data == nullptr ) {
    return;
  }
  const Signal *signal = network->GetSignal(data->Ident(), data->Name());
  if (signal == nullptr) {
    return;
  }

  std::ostringstream title;
  title << signal->Name();
  if (!signal->Comment().empty()) {
    title << " - " << signal->Comment();
  }
  title << "/" << file->Name();

  if (!title.str().empty()) {
    title << "/";
  }
  auto& app = wxGetApp();
  // Create the observer list
  auto observer_list = std::make_unique<SignalObserverList>();
  auto observer = std::make_unique<SignalObserver>(*signal);
  observer_list->push_back(std::move(observer));
  file->ReparseMessageList();
  const auto* obs = observer_list->front().get();
  if (obs == nullptr || obs->NofValidSamples() < 2) {
    wxMessageBox("There is not enough valid samples to plot");
    return;
  }
  // Produce a CSV file with the data for later use with the gnuplot script
  auto csv_file = CreateCsvFile(*observer_list);
  auto gp_file = CreateGnuPlotFile(*observer_list, csv_file, title.str());
  if (csv_file.empty() || gp_file.empty()) {
    wxMessageBox("Failed to create CSV or GP files.\nMore information in log file.");
    return;
  }
#if (_MSC_VER)
  boost::process::spawn(app.GnuPlot(), "--persist", gp_file, boost::process::windows::hide);
#else
  // TODO: how to hide?
  boost::process::spawn(app.GnuPlot(), "--persist", gp_file);
#endif

}
`

**Comment by Murmele** [comment]
@ihedvall I created already a few tests for labplot. You might be interested in it. I used a logfile I got and a dbc file and just changed the variable names
https://invent.kde.org/education/labplot/-/blob/work/blf_dbclib_ihedvall/tests/import_export/CAN/BLFFilterTest.cpp#L549

**Comment by ihedvall** [comment]
I assume that you are using the tomilo BLF reader. I think there should be a matching BLF and DBC files in his unit tests.

**Comment by ihedvall** [comment]
Or maybe not any DBC files in tomli.

CSS Electronics have some matching DBC + MDF files that I have been using.

Maybe the DBC example only should include the parsing of DBC file.

**Comment by Murmele** [comment]
> 

I don't think so, because the example should represent the usage of (all) features. Currently I don't know how to use it. I would be happy if I have one ^^. 
The problem is that the incomming data can be from mdf, blf, ... so I think showing how to use it generic would be nice

**Comment by ihedvall** [comment]
If we should have something running, We cannot use MDF or BLF in the example, so I propose that we add a DBC file and do a support function that generate messages. How about letting the library handle signal value conversion to message bytes?

**Comment by Murmele** [comment]
> 

Yes exactly, because of that just adding an example like:
```
 std::vector<uint8_t> data{0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8};
    const dbc::Message* message = network->GetMessage(234);
    if (message) {
        //message.ParseMessage()
    }
```
? But right know I did not find out which function I have to use to do something like that?

**Comment by ihedvall** [comment]
You should use DbcFile::ParseMessage(const DbcMessage& msg). The DbcMessage class is just a wrapper around timestamp, CAN ID and raw data bytes. It has nothing to do with the message class. The signals (latest) value can be read in Signal::EngValue<T>().

**Comment by Murmele** [comment]
Thanks I will check

**Comment by Murmele** [comment]
@ihedvall you mean like this?

**Comment by ihedvall** [comment]
This should work as an example. 

Just a hint is to check if the value is valid as J1939 protocol have this "all bits set" = invalid value. You should check the signals data type as many signals actually is enumerate why the EngValue function return strings. The ChannelValue function returns the enumerate index in these cases.

**Pull request merged**
